jenkinsci/performance-plugin

src/main/java/hudson/plugins/performance/JMeterParser.java

fixes-9522
On Macbook pro:
Current implementation:
Large 45 MB test file takes about 7 secs on a file being processed the first time.
Serialized results jtl file of about 27 MB takes  6 secs.
With the fix of using BufferedInputStream and BufferedOutputStream.
Large 45 MB test file takes about 3 secs on a file being processed the first time.
Serialized results jtl file of about 27 MB takes  1.5 secs.

performance displaying graph with large jtl file

---

src/main/java/hudson/plugins/performance/PerformanceReport.java

The original parser lookup in ifSummarizerParsedUsed is not comptaible with flexible publisher, because the performance publisher is not directly in buildAction.getBuild().getProject().getPublishersList(), but wrapped inside publisher list of flexible publisher. It will result in NPE because buildAction.getBuild().getProject().getPublishersList().get(PerformancePublisher.class) return null.
We can just simply look up with buildAction.getParserByDisplayName directly instead of looping the project publisher list to check for JmeterSummarizer and Iago parser. The parser list is already there in buildAction. This way the code is simpler, and we can avoid complicated lookup when this publisher is under flexible publisher.

Compatible with flexible publisher

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/test/java/hudson/plugins/performance/PerformancePublisherTest.java

Because it is possible to have for a same job different build options, build status should not be systematically failed if result files were not finded.
I added a checkbox option in job configuration page in order to manage build status for that need.

Add checkbox in job config in order to choose build status when result performance file are not present

---

src/main/java/hudson/plugins/performance/PerformanceReport.java
src/main/java/hudson/plugins/performance/UriReport.java
src/main/resources/hudson/plugins/performance/UriReport/index.jelly
src/test/java/hudson/plugins/performance/ThroughputReportTest.java
src/test/java/hudson/plugins/performance/ThroughputUriReportTest.java
src/test/java/hudson/plugins/performance/UriReportTest.java

Add shorturi method back to UriReport. This method is used in Jelly script which displays the uri used for test.
Removed sample values need to be added back for the uriReport page.
URI column is redundant on the uriReport page.

fixes-27350

---

src/main/resources/hudson/plugins/performance/PerformanceReportMap/index.jelly

Re-add link to uri report, on the performance report page.
https://issues.jenkins-ci.org/browse/JENKINS-27350

JENKINS-27350: Fix for uri column value not shown as link

---

src/main/resources/hudson/plugins/performance/UriReport/index.jelly

Created copy of test/resources/JMeterResults.jtl test file. Added additional data values with timestamps as specified in issue JENKINS-10642.
Manually tested sorting using a copy of JMeterResults.jtl file as the data source in Jenkins.

JENKINS-10642: Sort correctly on date values

---

src/main/java/hudson/plugins/performance/JUnitParser.java
src/test/java/hudson/plugins/performance/JUnitParserTest.java
src/test/resources/TEST-JUnitResults-noTimeAttribute.xml

Check for null value for time taken to execute a Junit test. If it is null, use 0 as the time value.
The right fix would probably be to use change HttpSample.duration attribute from long to Long and set it to null when no information is provided. Doing this type of a change is probably a larger change affecting various parts of the plugin.
This fix is good enough for the time being.

Use 0 for time when no value is provided in Junit test result

---

src/main/java/hudson/plugins/performance/JUnitParser.java
src/test/java/hudson/plugins/performance/JUnitParserTest.java
src/test/resources/TEST-JUnitResults-success-failure-error.xml

https://issues.jenkins-ci.org/browse/JENKINS-18811
There was a duplicate else if for "failure", instead of "error".

JENKINS-18811: Fix for Junit parser not handling errors.

---

src/main/java/hudson/plugins/performance/JMeterCsvParser.java
src/main/java/hudson/plugins/performance/JMeterParser.java
src/test/java/hudson/plugins/performance/JMeterParserTest.java

- Changed to use correct default CSV format.
- Added additional verification in test to verify jtl file
with CSV data is being parsed correctly.

JENKINS-30963: Fix for parsing jtl with CSV data.

---

src/main/java/hudson/plugins/performance/JMeterCsvParser.java
src/test/java/hudson/plugins/performance/JMeterCsvParserTest.java

When JMeter parser is used and a csv file contains header line, a number format exception is thrown.
Fix is to check if the first line is a header and skip the line if it is a header.
Note: Noticed that if there was a test for the constructor with glob only, this issue
would have been caught in testing.
Test added and refactored for cleanup.

[FIXES JENKINS-28787]: Fixes number format exception

---

.travis.yml
pom.xml
src/main/java/hudson/plugins/performance/AbstractParser.java
src/main/java/hudson/plugins/performance/PerformanceProjectAction.java
src/main/java/hudson/plugins/performance/PerformanceReportMap.java
src/main/java/hudson/plugins/performance/TestSuiteReportDetail.java
src/main/resources/hudson/plugins/performance/AbsoluteConstraint/config.jelly
src/main/resources/hudson/plugins/performance/GraphConfigurationDetail/index.jelly
src/main/resources/hudson/plugins/performance/IagoParser/config.jelly
src/main/resources/hudson/plugins/performance/JMeterCsvParser/config.jelly
src/main/resources/hudson/plugins/performance/PerformanceProjectAction/floatingBox.jelly
src/main/resources/hudson/plugins/performance/PerformanceProjectAction/index.jelly
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/main/resources/hudson/plugins/performance/PerformanceReportMap/index.jelly
src/main/resources/hudson/plugins/performance/PerformanceReportParser/config.jelly
src/main/resources/hudson/plugins/performance/RelativeConstraint/config.jelly
src/main/resources/hudson/plugins/performance/TestSuiteReportDetail/index.jelly
src/main/resources/hudson/plugins/performance/TrendReportDetail/index.jelly
src/main/resources/hudson/plugins/performance/TrendReportGraphs/index.jelly
src/main/resources/hudson/plugins/performance/UriReport/index.jelly
src/main/resources/hudson/plugins/performance/tags/captionLine.jelly
src/main/resources/hudson/plugins/performance/tags/summaryTable.jelly
src/main/resources/hudson/plugins/performance/tags/summaryTableSummarizer.jelly
src/main/resources/index.jelly

update parent pom version

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly

PR https://github.com/jenkinsci/performance-plugin/pull/73 was incomplete and was missing some getter & setters.
Its now possible to use the snippet generator without any issues.

[JENKINS-32650] follow up to PR #73

---

src/main/java/hudson/plugins/performance/AbstractParser.java
src/main/java/hudson/plugins/performance/AbstractReport.java

I have several projects that use **performance-plugin** with a huge quantity of jmeter result.
- The cache implemented cause very often jenkins  run out of memory. Using `softValues` allow to free cache memory when jenkins run out of memory.
- To reduce CPU usage I remove `synchronized` block by using `ThreadLocal` `DecimalFormat`.
Thx for your plugin.

Improve CPU and memory usage on heavy performance test.

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

Hi - we burned a few hours trying to figure out what was going wrong when trying to use this plugin, and noticed that these code paths are eating the exceptions. Any chance that this logging could be added to save some future users (including myself) some debugging time?
This would address https://issues.jenkins-ci.org/browse/JENKINS-40994

Logging exceptions to ease debugging

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

Certain codepaths that should result in setting a build to unstable don't seem to be setting the run result.

Setting build results for certain unstable result codepaths

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

Also logging stacktrace for exceptions.
Not sure why https://jenkins.ci.cloudbees.com/job/plugins/job/performance-plugin/212/ had unstable tests, then https://jenkins.ci.cloudbees.com/job/plugins/job/performance-plugin/213/ that ran right after was fine. All tests pass locally.

Fixing another unstable codepath that can result in a NPE.

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

This fixes the problem described here:
https://groups.google.com/forum/#!searchin/codename-taurus/rodrigues%7Csort:relevance/codename-taurus/kCXkIOyynio/hGUMbHmvFAAJ

If we have no parsedReports, do not access a null pointer.

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/java/hudson/plugins/performance/PerformanceReportMap.java
src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java
src/main/java/hudson/plugins/performance/data/ReportValueSelector.java
src/main/java/hudson/plugins/performance/details/TestSuiteReportDetail.java
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/test/java/hudson/plugins/performance/AbstractGraphGenerationTest.java
src/test/java/hudson/plugins/performance/PerformanceReportMapTest.java
src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionGraphTest.java
src/test/java/hudson/plugins/performance/data/ReportValueSelectorTest.java
src/test/java/hudson/plugins/performance/details/TestSuiteReportDetailTest.java
src/test/java/hudson/plugins/performance/parsers/JMeterTestHelper.java

Performance reports can be evaluated with the "Use Relative thresholds for build comparison" option. The comparison uses either average, median or percentile response times. Regardless of the choice, the graphs are charted using the average time. 
In my project the average values are pretty crazy due to outliers, but the median values are relatively stable. The comparison is configured to use median values and the tests pass. However, the graphs show averages instead of medians. This is not obvious and causes confusion, because based on the graphs the tests should be failing. 
This PR changes the graphs so that if median/percentile comparison is used, then the graphs will also use median/percentile values. I would be most interested in your comments on 
- whether this functionality makes …

choose graph type based on failure condition

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

PR #109 missed one setter when adding @DataBoundSetter annotations. 
Impact: when trying to change "Unstable % Range (-)" in job configuration, then the value is always saved as zero.

fix saving RelativeUnstableThresholdNegative

---

pom.xml
src/main/java/hudson/plugins/performance/workflow/WorkflowActionsFactory.java
src/test/java/hudson/plugins/performance/workflow/WorkflowActionsFactoryTest.java

The PerformanceProjectAction gets added to every pipeline run. This Performance trend is always empty:
This PR simplifies the WorkflowActionsFactory, so that only runs containing the PerformanceBuildAction are getting the PerformanceProjectAction added.
Furthermore i used 'mvn tidy:pom' to sort the pom.xml and increment some workflow dependencies.

add PerformanceProjectAction only to runs, which contain PerformanceBuildAction

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

Proper handling of existing reports for relative comparisons (JENKINS-46046)

Fix JENKINS-46046

---

.travis.yml
src/main/java/hudson/plugins/performance/PerformancePublisher.java

This fixes the garbled console output the Publisher produces for Relative Threshold comparison in Standard Mode

Implement fixed-size column width logging of relative comparison results

---

src/main/java/hudson/plugins/performance/reports/ConstraintReport.java
src/test/java/hudson/plugins/performance/reports/ConstraintReportTest.java

When there's more than just a few constraints, the Publisher log output in expert mode gets cluttered with successful constraint evaluation details.
An additional summary table makes the failing ones more obvious, for example:
```
Summary of failed constraints:
Report     Testcase   Metric     Operator                  Value Level
result.csv *          90% Line   not be greater than     10.000% Error
result.csv login      Average    not be greater than        3000 Warning    
```

Add summary table of failed constraints for Publisher log in expert mode

---

.travis.yml
src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/java/hudson/plugins/performance/constraints/AbsoluteConstraint.java
src/main/java/hudson/plugins/performance/constraints/AbstractConstraint.java
src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
src/main/java/hudson/plugins/performance/reports/ConstraintReport.java
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/main/resources/hudson/plugins/performance/PerformancePublisher/config.properties
src/test/java/hudson/plugins/performance/constraints/ConstraintCheckerTest.java
src/test/java/hudson/plugins/performance/reports/ConstraintReportTest.java

The console log output becomes cluttered especially when there are a lot of Constraints. 
As each evaluated Constraint can be interpreted as a test case, it is appropriate to report the outcome in JUnit format which can then be processed via existing Jenkins functionality, e.g. `junit` post-build action, test results on dashboards including trends etc.

Add option to write a JUnit report file to the job's workspace

---

src/main/java/hudson/plugins/performance/parsers/ParserDetector.java
src/test/java/hudson/plugins/performance/parsers/ParserDetectorTest.java

My try to fix [JENKINS-47808].
The first commit is here to reproduce the bug (with an infinite inputstream to simulate huge XML file).
The second commit fix the bug by using a StAX implementation to detect the XML file type.

[JENKINS-47808] Fix OutOfMemoryException when parsing huge JMeter XML result file

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java

Fix: 
When running on a Slave node, the Performance Publisher's JUnit output file would not be written to the (remote) workspace correctly.

Fix Publisher JUnit output to Slave workspace

---

src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java

This fixes the currently ambiguous/misleading test case failure message for relative constraints.

Better JUnit report failure message

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
src/main/java/hudson/plugins/performance/parsers/WrkSummarizerParser.java
src/main/java/hudson/plugins/performance/reports/PerformanceReport.java
src/main/java/hudson/plugins/performance/reports/UriReport.java
src/main/java/hudson/plugins/performance/tools/SafeMaths.java
src/test/java/hudson/plugins/performance/tools/SafeMathsTest.java

If tests are finishing faster than 1s, we get this stack trace:
```
Performance: Parsing JMeter report file '/data/jenkins/project/jobs/module__task-TR-5539_Performance_test/builds/15/performance-reports/Taurus/stats.xml'.
Performance: Failed to parse file '/data/jenkins/project/jobs/module__task-TR-5539_Performance_test/builds/15/performance-reports/Taurus/stats.xml': / by zero
java.lang.ArithmeticException: / by zero
at hudson.plugins.performance.reports.PerformanceReport.addSample(PerformanceReport.java:200)
at hudson.plugins.performance.parsers.TaurusParser.readFromXML(TaurusParser.java:78)
at hudson.plugins.performance.parsers.TaurusParser.parse(TaurusParser.java:42)
at hudson.plugins.performance.parsers.AbstractParser.parse(AbstractParser.java:81)
at …
```

Add a safeDivide() method and use it where divisions by 0 can occur

---

src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/main/resources/hudson/plugins/performance/build/PerformanceTestBuild/config.jelly

Sorry, turns out that data migration doesn't like what I did in #182
[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.

[JENKINS-55787] Switch from table to entry

---

src/main/java/hudson/plugins/performance/parsers/AbstractParser.java
src/test/java/hudson/plugins/performance/parsers/AbstractParserTest.java

A bug in `AbstractParser.loadSerializedReport` makes the report caching ineffective and leads to parsing for previously cached reports:
https://github.com/jenkinsci/performance-plugin/blob/performance-3.16/src/main/java/hudson/plugins/performance/parsers/AbstractParser.java#L147
```
PerformanceReport report = CACHE.getIfPresent(serialized);
if (report == null && file.exists() && file.canRead()) {
// deserialize...
}
return null; // THIS WILL CAUSE THE CALLER TO RE-PARSE
```

Fix ineffective report cache

---

src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/java/hudson/plugins/performance/constraints/AbstractConstraint.java
src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
src/main/java/hudson/plugins/performance/constraints/blocks/PreviousResultsBlock.java
src/main/java/hudson/plugins/performance/data/ConstraintSettings.java
src/main/resources/hudson/plugins/performance/constraints/RelativeConstraint/config.jelly
src/test/java/hudson/plugins/performance/constraints/ConstraintCheckerTest.java

The Performance Publisher's "Expert Mode" currently has two options for "Relative Constraints":
- Compare with number of previous builds
- Compare with builds within a time frame
However, there is no option to compare with a specific build number (which even the "Standard Mode" can do).
Since the addition of the baseline build setting in #178 for calculating report tables, it would make sense to use the same baseline build for "Relative Constraint" evaluations.
The challenge is not to break existing Jobs and Pipelines, which this PR addresses by leaving existing configuration fields and their existing values unchanged, but changing them to a String field with the same representation, namely in `PreviousResultsBlock`:
```
public static final String PREVIOUS = "true", TIMEFRAME = "false", …
```

Add baseline comparison option for Relative Constraint

---

src/main/java/hudson/plugins/performance/parsers/LocustParser.java
src/main/java/hudson/plugins/performance/parsers/ParserDetector.java
src/test/java/hudson/plugins/performance/parsers/LocustParserTest.java
src/test/java/hudson/plugins/performance/parsers/ParserDetectorTest.java
src/test/resources/test_results_requests.csv

This code is implementation of [locustio](https://locust.io/) reports parser. 
It expects the reports generated in Locust *csv format as described in [documentation](https://docs.locust.io/en/stable/retrieving-stats.html?highlight=csv).

Adding Locust report files parser.

---

src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java

The plugin currently publishes response time charts for the build based on the stored sample data, both on the `/performance/trendReport` and  `/performance/uriReport` page.
These charts are line charts, with each individual sample being plotted and connected with straight lines (first example below).
This is not ideal as it hides significant details (clustering, queuing, gaps, outlier etc.) and would be much better presented as scatter plot, i.e. individual dots without lines in between (second example below).
This PR implements this change, which is purely affecting presentation of the same data.

Response times scatter plot

---

src/main/java/hudson/plugins/performance/TrendReportGraphs.java
src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java
src/main/java/hudson/plugins/performance/reports/UriReport.java
src/main/resources/hudson/plugins/performance/Messages.properties
src/main/resources/hudson/plugins/performance/reports/UriReport/index.jelly

For each test run, on the `/performance/uriReport` page the plugin currently plots response times over time.
However, it would be nice and easy to present more charts as the build contains all the sample data.
This PR adds two more charts (example below): 
- Response time percentiles
- Request throughput over time (in requests per minute)
Happy to add unit tests if this PR idea is generally accepted.

Add percentile and throughput chart to URI report page

---

src/main/java/hudson/plugins/performance/TrendReportGraphs.java
src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java
src/main/java/hudson/plugins/performance/reports/UriReport.java
src/main/resources/hudson/plugins/performance/reports/UriReport/index.jelly

Similar to #193, the URI report page may show how error responses are distributed over time in a scatter plot.
Example:

Add error chart to URI report page

---

.travis.yml
src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java
src/main/resources/hudson/plugins/performance/build/PerformanceTestBuild/config.jelly
src/main/resources/hudson/plugins/performance/build/PerformanceTestBuild/config.properties
src/test/java/hudson/plugins/performance/build/PerformanceTestBuildTest.java

On our machines, we are installing 'python' and 'virtualenv' using the Custom Tools in Jenkins. They should change the PATH environment, but unfortunately the plugin does not pick up this changes path (I believe it is a known bug in Jenkins -- will try to find the issue).
I added a parameter (in the advanced block of the build, because it is not necessary to set this parameter) to set the path to the virtualenv-binary to use. I made it possible to use EnvVar to set the path, because not all our machines are installed in the same path (eg Linux vs Windows) and I would like to be able to have a single configuration to work on all our machines.

Added the posibillity to explicitly set the path to 'virtualenv'

---

src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly
src/main/resources/hudson/plugins/performance/constraints/AbsoluteConstraint/config.jelly
src/main/resources/hudson/plugins/performance/constraints/RelativeConstraint/config.jelly
src/main/resources/lib/performance/blockWrapper.jelly

See [JENKINS-64990](https://issues.jenkins.io/browse/JENKINS-64990).
The Performance plugin is currently broken when running Jenkins 2.264+ (or LTS 2.277.x / 2.289.x). Several blocks of the `PerformancePublisher` form use tables, in ways which conflict with the recent(-ish) [tables-to-divs](https://www.jenkins.io/doc/developer/views/table-to-div-migration/) conversion of the Jenkins UI.
This PR tries to fix that. It changes three jelly files:
- `.../PerformancePublisher/config.jelly`
- `.../constraints/AbsoluteConstraint/config.jelly`
- `.../constraints/RelativeConstraint/config.jelly`
All changes are made in the spirit of keeping compatibility with both layouts, tables-based (up to 2.2.63.x) and divs-based (2.264+). One trick I've used is a `blockWrapper` Jelly tag, inspired by the …

[JENKINS-64990] tables-to-divs: compatibility with Jenkins 2.264+

---

src/main/java/hudson/plugins/performance/parsers/AbstractParser.java
src/test/java/hudson/plugins/performance/PerformancePublisherTest.java
src/test/resources/JMeterPublisher_formatted_timeStamp.csv

Fixes the `UnsupportedOperationException: Refusing to marshal java.text.SimpleDateFormat for security reasons` by re-applying patch from #170

Fix UnsupportedOperationException: Refusing to marshal java.text.SimpleDateFormat for security reasons

---

Jenkinsfile
src/main/java/hudson/plugins/performance/PerformancePublisher.java
src/main/java/hudson/plugins/performance/PerformanceReportMap.java
src/main/java/hudson/plugins/performance/actions/PerformanceBuildAction.java
src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java
src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java
src/main/java/hudson/plugins/performance/constraints/AbstractConstraint.java
src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
src/main/java/hudson/plugins/performance/data/HttpSample.java
src/main/java/hudson/plugins/performance/parsers/AbstractParser.java
src/main/java/hudson/plugins/performance/parsers/IagoParser.java
src/main/java/hudson/plugins/performance/parsers/JMeterCsvParser.java
src/main/java/hudson/plugins/performance/parsers/JMeterParser.java
src/main/java/hudson/plugins/performance/parsers/JmeterSummarizerParser.java
src/main/java/hudson/plugins/performance/parsers/LocustParser.java
src/main/java/hudson/plugins/performance/parsers/ParserDetector.java
src/main/java/hudson/plugins/performance/parsers/TaurusParser.java
src/main/java/hudson/plugins/performance/parsers/WrkSummarizerParser.java
src/main/java/hudson/plugins/performance/reports/ConstraintReport.java
src/main/java/hudson/plugins/performance/reports/PerformanceReport.java
src/main/java/hudson/plugins/performance/reports/UriReport.java

Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21 on Linux.
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull …

Update parent POM, update dependencies, solve spotbug errors, test with Java 21 #105

---

.mvn/extensions.xml
pom.xml

- Bumps [org.codehaus.plexus:plexus-utils](https://github.com/codehaus-plexus/plexus-utils) from 4.0.0 to 4.0.1. (#255)
- Bumps [io.jenkins.tools.incrementals:git-changelist-maven-extension](https://github.com/jenkinsci/incrementals-tools) from 1.7 to 1.8. (#256)
- Bumps [org.jenkins-ci.plugins:plugin](https://github.com/jenkinsci/plugin-pom) from 4.78 to 4.81. (#257)

Bump dependencies
