src/main/java/hudson/plugins/performance/AbstractReport.java
Don't change JVM Locale
Fix for https://issues.jenkins-ci.org/browse/JENKINS-15736 based on evernat suggested fix
=> Prevent JVM language change, update AbstractReport.java

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/PerformanceReportMap.java
=> Generate performance report even if previous builds are still running

.gitignore, src/main/java/hudson/plugins/performance/AbstractReport.java, src/main/java/hudson/plugins/performance/HttpSample.java, src/main/java/hudson/plugins/performance/IagoParser.java, src/main/java/hudson/plugins/performance/JMeterParser.java, src/main/java/hudson/plugins/performance/PerformanceProjectAction.java, src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/PerformanceReport.java, src/main/java/hudson/plugins/performance/PerformanceReportMap.java, src/main/java/hudson/plugins/performance/TestSuiteReportDetail.java, src/main/java/hudson/plugins/performance/ThroughputUriReport.java, src/main/java/hudson/plugins/performance/TrendReportGraphs.java, src/main/java/hudson/plugins/performance/UriReport.java, src/test/java/hudson/plugins/performance/IagoParserTest.java, src/test/java/hudson/plugins/performance/PerformanceReportTest.java, src/test/java/hudson/plugins/performance/ThroughputReportTest.java, src/test/java/hudson/plugins/performance/ThroughputUriReportTest.java, src/test/java/hudson/plugins/performance/UriReportTest.java
This pull request introduces improvements as described in detail on https://issues.jenkins-ci.org/browse/JENKINS-26975
In short, three issues have been addressed, that each improve disc, memory and CPU utilization of the plugin. These changes turned the plugin from unworkable to lightweight in our setup.
=> [FIXED JENKINS-26975] Significant performance boost for Performance Plugin

src/main/java/hudson/plugins/performance/ThroughputUriReport.java
=> fixes JENKINS-27373

src/main/resources/hudson/plugins/performance/Messages.properties
=> Cleaned up English localization.

src/main/resources/hudson/plugins/performance/PerformanceReportMap/index.jelly, src/main/resources/hudson/plugins/performance/TrendReportGraphs/index.jelly
fixes an issue when URI's details were not shown on some pages
=> [JENKINS-28733] fix

src/main/java/hudson/plugins/performance/PerformanceReport.java, src/test/java/hudson/plugins/performance/PerformanceReportTest.java, src/test/resources/JMeterResultsOneSample.jtl, src/test/resources/JMeterResultsTenSamples.jtl, src/test/resources/JMeterResultsThreeSamples.jtl
New tests passing. Implemented suggestion in Jira.
=> JENKINS-22871: Wrong index when calculating 90Line.

src/main/java/hudson/plugins/performance/JMeterCsvParser.java, src/main/java/hudson/plugins/performance/PerformanceProjectAction.java, src/test/java/hudson/plugins/performance/ThroughputUriReportTest.java
1 sample and duration of 1.
Test refactoring to reduce duplicate code.
Refactoring to remove unnecessary if/else logic.
=> Added test to verify divide by zero exception is not thrown with

pom.xml, src/main/java/hudson/plugins/performance/AbstractParser.java, src/main/java/hudson/plugins/performance/PerformanceBuildAction.java, src/main/java/hudson/plugins/performance/PerformanceProjectAction.java, src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/PerformanceReport.java, src/main/java/hudson/plugins/performance/PerformanceReportMap.java, src/main/java/hudson/plugins/performance/PerformanceReportParser.java, src/main/java/hudson/plugins/performance/PerformanceReportParserDescriptor.java, src/main/java/hudson/plugins/performance/TestSuiteReportDetail.java, src/main/java/hudson/plugins/performance/TrendReportGraphs.java, src/main/java/hudson/plugins/performance/UriReport.java, src/main/java/hudson/plugins/performance/constraints/AbsoluteConstraint.java, src/main/java/hudson/plugins/performance/constraints/AbstractConstraint.java, src/main/java/hudson/plugins/performance/constraints/ConstraintChecker.java, src/main/java/hudson/plugins/performance/constraints/ConstraintDescriptor.java, src/main/java/hudson/plugins/performance/constraints/ConstraintFactory.java, src/main/java/hudson/plugins/performance/constraints/ConstraintReport.java, src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
this PR tries to make the Performance Plugin Pipeline compatible.
@jenkinsci/code-reviewers i implemented SimpleBuildStep as described [here](https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md). However the 'performanceReports' step does not show up in the snippet generator
=> [JENKINS-32650] make Performance Plugin Pipeline compatible

src/main/java/hudson/plugins/performance/TestSuiteReportDetail.java
See [JENKINS-40254](https://issues.jenkins-ci.org/browse/JENKINS-40254) for more info.
=> Show the average for the uri on the 'Performance Trend Per Test Case' view as well.

src/main/java/hudson/plugins/performance/PerformanceProjectAction.java, src/main/java/hudson/plugins/performance/TestSuiteReportDetail.java, src/test/java/hudson/plugins/performance/TestSuiteReportDetailTest.java
Had to refactor doRespondingTimeGraphPerTestCaseMode method and extracted getChartDatasetBuilderForBuilds from it to make it a bit easier to test. Also I removed some unused parameters from the constructor of TestSuiteReportDetail.
Follow-up to #75.
=> Added test for JENKINS-40254

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/test/java/hudson/plugins/performance/PerformancePublisherTest.java, src/test/java/hudson/plugins/performance/constraints/ConstraintTest.java
see also [JENKINS-26535](https://issues.jenkins-ci.org/browse/JENKINS-26535)
=> [JENKINS-41086] avoid wildcard in @DataBoundConstructor

src/test/java/hudson/plugins/performance/PerformancePublisherTest.java
https://groups.google.com/forum/#!searchin/codename-taurus/rodrigues%7Csort:relevance/codename-taurus/kCXkIOyynio/hGUMbHmvFAAJ
=> added test for NPE

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/parsers/ParserFactory.java, src/test/java/hudson/plugins/performance/parsers/ParserFactoryTest.java
https://issues.jenkins-ci.org/browse/JENKINS-43503
=> Fix JENKINS-43503  

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/parsers/ParserFactory.java, src/test/java/hudson/plugins/performance/parsers/ParserFactoryTest.java
https://issues.jenkins-ci.org/browse/JENKINS-43438
=> Fixed  43438

.travis.yml, src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java, src/main/java/hudson/plugins/performance/parsers/ParserDetector.java, src/test/java/hudson/plugins/performance/build/PerformanceTestBuildTest.java, src/test/java/hudson/plugins/performance/parsers/ParserDetectorTest.java, src/test/resources/TEST-results.xml
https://issues.jenkins-ci.org/browse/JENKINS-44317
=> fixed 44317

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/data/ConstraintSettings.java
Replace BuildListener with TaskListener (which is only used for logging progress to console)
=> Fix JENKINS-45633 

src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
Added null check for Snippetizer form validation
=> Fix JENKINS-45985

src/main/java/hudson/plugins/performance/constraints/blocks/PreviousResultsBlock.java
Fixed binding mismatch between Jelly and Describable fields via tweaking JSON form data
=> Fix JENKINS-45988

src/test/java/hudson/plugins/performance/parsers/LoadRunnerParserTest.java
Remove time zone dependency by using relative times.
=> Fix incorrect test for #154

src/main/java/hudson/plugins/performance/constraints/RelativeConstraint.java
This PR fixes an issue with the Publisher: 
The very first build fails when a relative constraint finds no previous builds to compare to. The first build should pass instead. 
Similarly, the form validation should allow for one more previous build to be entered than there are already, as there will be one more the next time the plugin runs the post-build constraint check.
=> Relative Constraint should not fail the very first build

docs/Changelog.md, pom.xml, src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java, src/test/java/hudson/plugins/performance/PerformancePipelineTest.java
=>  FIX: parse Taurus tool parameters

docs/Changelog.md, src/main/java/hudson/plugins/performance/parsers/AbstractParser.java
https://issues.jenkins-ci.org/browse/JENKINS-51703
=> Fix/support JEP-200

src/main/java/hudson/plugins/performance/parsers/JUnitParser.java
JUnit timestamp parsing to display correct performence trend graph.
=> JUnit timestamp parsing

src/main/java/hudson/plugins/performance/parsers/JMeterCsvParser.java, src/main/java/hudson/plugins/performance/reports/PerformanceReport.java, src/main/java/hudson/plugins/performance/reports/UriReport.java, src/main/java/hudson/plugins/performance/tools/SafeMaths.java, src/main/resources/hudson/plugins/performance/tags/summaryTable.jelly, src/test/java/hudson/plugins/performance/parsers/JMeterCsvParserTest.java, src/test/resources/JMeterCsvResults2.csv, src/test/resources/JMeterCsvResults3.csv
Hello,
Other fixed issues by PR:
- roundTwoDecimals uses BigDecimal constructor with double
- Use try / with resources
- Replace Exception by more accurate exceptions
- Use diamond constructor where possible
Hope
Regards
Philippe M.
=> Add network traffic when parsing JMeter CSV and fix other issues

LICENSE
=> Add explicit MIT license since this seems to be the default license for

docs/Reporting.md
- Update tools links
- Fix typo in doc
- Improve Pipeline documentation
=> Improve documentation Reporting.md

src/main/java/hudson/plugins/performance/PerformanceReportMap.java
As per discussion https://github.com/jenkinsci/performance-plugin/pull/179#discussion_r277949837
=> Remove redundant report loading

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/PerformanceReportMap.java, src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java, src/main/java/hudson/plugins/performance/parsers/IagoParser.java, src/main/java/hudson/plugins/performance/parsers/JMeterCsvParser.java, src/main/java/hudson/plugins/performance/parsers/JMeterParser.java, src/main/java/hudson/plugins/performance/parsers/JUnitParser.java, src/main/java/hudson/plugins/performance/parsers/JmeterSummarizerParser.java, src/main/java/hudson/plugins/performance/parsers/LoadRunnerParser.java, src/main/java/hudson/plugins/performance/parsers/LocustParser.java, src/main/java/hudson/plugins/performance/parsers/PerformanceReportParser.java, src/main/java/hudson/plugins/performance/parsers/TaurusParser.java, src/main/java/hudson/plugins/performance/parsers/WrkSummarizerParser.java, src/main/java/hudson/plugins/performance/reports/AbstractReport.java, src/main/java/hudson/plugins/performance/reports/PerformanceReport.java, src/main/resources/hudson/plugins/performance/PerformancePublisher/config.jelly, src/main/resources/hudson/plugins/performance/PerformanceReportMap/index.jelly, src/test/java/hudson/plugins/performance/PerformancePublisherTest.java, src/test/java/hudson/plugins/performance/PerformanceReportMapTest.java, src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionTest.java, src/test/java/hudson/plugins/performance/constraints/ConstraintTest.java
Copy of https://github.com/jenkinsci/performance-plugin/pull/195
=> Feature to enable/disable trend graphs in performance report [JENKINS-64638]

.mvn/extensions.xml, .mvn/maven.config, pom.xml, src/main/java/hudson/plugins/performance/reports/UriReport.java, src/test/java/hudson/plugins/performance/BaselineComparisonTest.java, src/test/java/hudson/plugins/performance/PerformancePipelineTest.java, src/test/java/hudson/plugins/performance/PerformanceReportMapTest.java, src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionGraphTest.java, src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionTest.java, src/test/java/hudson/plugins/performance/constraints/ConstraintCheckerTest.java, src/test/java/hudson/plugins/performance/constraints/ConstraintFactoryTest.java, src/test/java/hudson/plugins/performance/data/ReportValueSelectorTest.java, src/test/java/hudson/plugins/performance/details/GraphConfigurationDetailTest.java, src/test/java/hudson/plugins/performance/details/TestSuiteReportDetailTest.java
Updates various build and runtime dependencies to the latest versions.
=> Update plugin POM and dependencies

src/main/java/hudson/plugins/performance/PerformancePublisher.java, src/main/java/hudson/plugins/performance/actions/PerformanceProjectAction.java, src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java, src/main/java/hudson/plugins/performance/workflow/WorkflowActionsFactory.java, src/test/java/hudson/plugins/performance/PerformancePublisherTest.java, src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionGraphTest.java, src/test/java/hudson/plugins/performance/build/PerformanceTestBuildTest.java, src/test/java/hudson/plugins/performance/parsers/ParserFactoryTest.java
Compatible with [`plugin-pom` 4.32](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.32).
=> EOL JSR 305

src/main/java/hudson/plugins/performance/parsers/JMeterParser.java, src/main/java/hudson/plugins/performance/parsers/JUnitParser.java, src/main/java/hudson/plugins/performance/parsers/ParserDetector.java, src/main/java/hudson/plugins/performance/parsers/TaurusParser.java
Potential fix for XXE vulnerability in Performance Plugin (SECURITY-2394 / CVE-2021-21701)
=> [SECURITY-2394] Prevent XXE

.github/dependabot.yml, .github/workflows/cd.yaml, .github/workflows/ci.yml, .gitignore, .mvn/maven.config, pom.xml, requirements.txt, src/test/java/hudson/plugins/performance/BaselineComparisonTest.java, src/test/java/hudson/plugins/performance/actions/PerformanceProjectActionGraphTest.java, src/test/java/hudson/plugins/performance/build/PerformanceTestBuildTest.java, src/test/java/hudson/plugins/performance/constraints/ConstraintCheckerTest.java, src/test/java/hudson/plugins/performance/reports/ConstraintReportTest.java
Implemented automated plugin release
=> Automated plugin release

Jenkinsfile, src/main/java/hudson/plugins/performance/constraints/AbstractConstraint.java, src/main/java/hudson/plugins/performance/parsers/PerformanceReportParser.java, src/main/java/hudson/plugins/performance/parsers/WrkSummarizerParser.java, src/main/java/hudson/plugins/performance/reports/ConstraintReport.java
=> Fix for javadoc issues

pom.xml
=> fix: support Jenkins 2.516.1
